project: recurrent_networks_copy
run_name: hess_copy_${model.architecture}_${model.hidden_dim}_${optimizer.lr}_${task.batch_size}
steps: 5000
log_every: 50
eval_every: 250
eval_steps: 1000
ckpt_every: 250
ckpt_metric: accuracy
save_best: true
precision: bfloat16
entity: phess2-massac
seed: 0
wandb_api_key: 5121db50fd49df0ad590e8c95f79f5d97d165512
feature_log_every: 500
feature_log_max_batches: 1
feature_save_dir: feature_logs/copy_default
disable_checkpointing: true
sweep_run: true
