project: recurrent_networks_copy
run_name: ostrow_copy_${model.architecture}_${model.hidden_dim}
steps: 50000
log_every: 50
eval_every: 50
eval_steps: 1000
ckpt_every: 50
ckpt_metric: accuracy
save_best: true
precision: bfloat16
entity: phess2-massac
seed: 0
wandb_api_key: 172a4c57ff0779bfbe96de3da444e9851729e3d9
feature_log_every: 50
feature_log_max_batches: 1
feature_save_dir: feature_logs/copy_default
length_generalization_fractions:
  - 2.0
  - 10.0
noise_generalization_stddevs:
  - 0.1
  - 0.5

