project: recurrent_networks_copy
run_name: copy_task
steps: 50000
log_every: 50
eval_every: 200
eval_steps: 10
ckpt_every: 500
ckpt_metric: accuracy
save_best: true
precision: bfloat16
entity: phess2-massac
seed: 1
wandb_api_key: 172a4c57ff0779bfbe96de3da444e9851729e3d9
feature_log_every: 500
feature_log_max_batches: 1
feature_save_dir: feature_logs/copy_default

