project: recurrent_networks_copy
run_name: hess_copy_${model.architecture}_${model.hidden_dim}_${optimizer.lr}_${optimizer.weight_decay}
steps: 25000
log_every: 500
eval_every: 5000
eval_steps: 1000
ckpt_every: 5000
ckpt_metric: accuracy
save_best: true
precision: bfloat16
entity: phess2-massac
seed: 0
wandb_api_key:
feature_log_every: 5000
feature_log_max_batches: 1
feature_save_dir: feature_logs/copy_default
disable_checkpointing: true
sweep_run: true
