project: recurrent_networks_kbit
run_name: hess_kbit_${model.rnn_nonlinearity}_${model.architecture}_lr_${optimizer.lr}_wd_${optimizer.weight_decay}
steps: 10000
log_every: 200
eval_every: 2000
eval_steps: 400
ckpt_every: 2000
ckpt_metric: mse
save_best: true
precision: bfloat16
entity: phess2-massac
seed: 0
wandb_api_key: 5121db50fd49df0ad590e8c95f79f5d97d165512
feature_log_every: 2000
feature_log_max_batches: 1
feature_save_dir: feature_logs/kbit_default
disable_checkpointing: true
sweep_run: true
