defaults:
  - task: copy
  - model: rnn
  - optimizer: adamw
  - train: copy_default
  - _self_

hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d_%H-%M-%S}

